version: "3"

services:
  contacts-app:
    container_name: contacts-app
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /.cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - /.cloud-cache/:/contacts-app:cached
    depends_on:
      - contacts-app
